### ISSUE TITLE
Is there a way to retrieve the ARN of the created certificate?

### ISSUE THREAD

**Issue by ima-tech** [dflook/cloudformation-dns-certificate#1]
I'm wondering if there's a way to retrieve the ARN of the created certificate, directly from CloudFormation.

**Comment by dflook** [comment]
Yes, as with [AWS::CertificateManager::Certificate](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-certificatemanager-certificate.html) providing the logical ID of the resource to the Ref function returns the certificate ARN.

For example (in yaml): `!Ref 'ExampleCertificate'`
