### ISSUE TITLE
Timeout Issues

### ISSUE THREAD

**Issue by DavidWells** [dflook/cloudformation-dns-certificate#10]
Hey first off, many thanks for the awesome custom resource. It's super helpful! 

It appears that everything is working correctly but I'm running into a timeout issue where the ACM cert gets stuck in a "pending validation" state.

Have you ever seen this before?

![image](https://user-images.githubusercontent.com/532272/82718387-12d10f00-9c57-11ea-94fb-cb078bfb9838.png)

The CNAME was successfully created in Route53

![image](https://user-images.githubusercontent.com/532272/82718400-1fedfe00-9c57-11ea-96df-e5e3b0bc6edb.png)

And the custom resource lambda is doing its job (per its logs)

![image](https://user-images.githubusercontent.com/532272/82718410-31cfa100-9c57-11ea-892d-823a0a240ad1.png)

However, when the max execution time hits, the stack creation fails 😅

Any ideas on how I might be able to resolve this?

Many thanks!

**Comment by dflook** [comment]
Hi, thanks for creating an issue!

The first thing I would try is creating the certificate manually and seeing if it validates after leaving it for a little longer that the resource allows - perhaps an hour.

Check if you can resolve the validation record yourself, e.g.:
```bash
$ dig _a98cbf......com
```
and see if you get the correct value back.

My guess is the zone delegation is not working. Check the NS record in the parent zone is correct.

**Comment by DavidWells** [comment]
Aha! I've figured it out. 

My regions did not match. `us-east-1` was set on the resource but the stack/API was in `us-west-1` 🙈. 

So the custom resource did it's thing and continues to check for a non-existent recordset. 

Closing this!

Thanks again for this awesome custom resource ❤️
