### ISSUE TITLE
DomainValidationOptions optional?

### ISSUE THREAD

**Issue by chekalsky** [dflook/cloudformation-dns-certificate#15]
Is it possible to make `DomainValidationOptions` optional as it is in CloudFormation?

**Comment by dflook** [comment]
Hello @chekalsky, could you tell me what you would use it for? The `DomainValidationOptions` are required to validate the certificate.

**Comment by chekalsky** [comment]
@dflook not always, I can validate manually with 3rd party provider, CloudFormation gives that ability.

**Comment by dflook** [comment]
As of version 2.0.0, DomainValidationOptions is optional
