### ISSUE TITLE
Warnings from cfn-lint about AWS partitions

### ISSUE THREAD

**Issue by CurryEleison** [dflook/cloudformation-dns-certificate#19]
`cfn-lint` issues a warning I3042 on the provided templates. I made a PR with a fix and provide more detail in the PR description: #18 . Feel free to close this without merging if you think it isn't necessary.

**Comment by dflook** [comment]
Hi @CurryEleison, how did you get rule I3042 to trigger? My version of cfn-lint (0.72.10) doesn't seem to.

**Comment by CurryEleison** [comment]
`cfn-lint` will exclude all checks beginning with `I` by default. So to repro you need to include all the cfn-lint checks with

```sh
cfn-lint -c I -- cloudformation.yaml
```
(this is clarified at https://github.com/aws-cloudformation/cfn-lint#info-rules )

Sorry for not realizing this. I was using a VS Code cfn-lint plugin that defaulted to run the informational checks and assumed it was the default also on the command line.

**Comment by dflook** [comment]
Resolved in #18
