### ISSUE TITLE
Using SubjectAlternativeNames causes unexpected behaviour

### ISSUE THREAD

**Issue by sirhc9** [dflook/cloudformation-dns-certificate#2]
Take the following example..

The lambda is unhappy because it appears to be looking for another HostedZoneId for *.mywebsite.com, however there isn't a documented location to put the next HostedZoneId or why it is needed since they would likely share the same zone.

> "DomainValidationOptions":[  
>          {  
>             "DomainName":"mywebsite.com",
>             "HostedZoneId":"123456789"
>          }
>       ],
>       "DomainName":"mywebsite.com",
>       "ValidationMethod":"DNS",
>       "SubjectAlternativeNames":[  
>          "*.mywebsite.com"
>       ],
>       "Tags":[  
>          {  
>             "Value":"Example Certificate",
>             "Key":"Name"
>          }
>       ]

**Comment by dflook** [comment]
Hi, thanks for creating an issue.

Right now it needs a DomainValidationOptions entry for each of the DomainName and SubjectAlternativeNames. With multiple DomainValidationOptions your example would look like:

```json
{
  "DomainValidationOptions": [
    {
      "DomainName": "mywebsite.com",
      "HostedZoneId": "123456789"
    },
    {
      "DomainName": "*.mywebsite.com",
      "HostedZoneId": "123456789"
    }
  ],
  "DomainName": "mywebsite.com",
  "ValidationMethod": "DNS",
  "SubjectAlternativeNames": [
    "*.mywebsite.com"
  ],
  "Tags": [
    {
      "Value": "Example Certificate",
      "Key": "Name"
    }
  ]
}
```

I agree this is a bug as it doesn't match the behaviour of AWS::CertificateManager::Certificate (which can just have DomainValidationOptions for the parent domain)

**Comment by dflook** [comment]
This should now work as expected

**Comment by sirhc9** [comment]
Can you also please add documentation for this feature for both activation through the parent domain and multiple domains?

**Comment by dflook** [comment]
I've added some more examples to the readme.

**Comment by sirhc9** [comment]
Love your work 👍
