### ISSUE TITLE
DeprecationWarning botocore.vendored.requests

### ISSUE THREAD

**Issue by CompuGlobalHyperMegaNet-VP** [dflook/cloudformation-dns-certificate#8]
Hi,

```
from botocore.vendored import requests
...
response = requests.put(event['ResponseURL'], json=event, headers={'content-type': ''})
```

raises this warning in the logs:

`/var/runtime/botocore/vendored/requests/api.py:67: DeprecationWarning: You are using the put() function from 'botocore.vendored.requests'. This is not a public API in botocore and will be removed in the future. Additionally, this version of requests is out of date. We recommend you install the requests package, 'import requests' directly, and use the requests.put() function instead. `

Given the short release cycles of boto3/botocore, it is possible that this will break in a not too distant future. It is possible to fix this before then?

Thanks in advance, 
BR.

**Comment by dflook** [comment]
Thanks for bringing this to my attention.

I'll work on a fix this week.
