### ISSUE TITLE
Ability to skip recordset creation for some domains

### ISSUE THREAD

**Issue by rjgys** [dflook/cloudformation-dns-certificate#9]
Hi,

I have a use case whereby the certificate contains some domains that are managed externally (outside of Route53). For these domains it would be useful to have an option to skip the attempt to create the validation records (otherwise the certificate creation fails).

Best regards,
RJ

**Comment by dflook** [comment]
The standard `AWS::CertificateManager::Certificate` resource has been updated to allow creation of DNS validated certificates now, by setting the `ValidationMethod`. It still doesn't actually create the validation records, but would that be OK for your use case?

**Comment by PhilippTreupel** [comment]
Hello, I have the same problem. For my external domains, I would like to have the validation information for the CName record simply printed (I use the serverless framework), i.e. whenever I do not specify a `HostedZoneId` with the `DomainName`. 
For the others, I would like to leave the creation automated. 
Can you adapt the code accordingly? 
Many thanks in advance.

**Comment by dflook** [comment]
In version 2.0.0 you no longer need a DomainValidationOption for all domains in the certificate. If there isn't one for a name, the validation records won't be created. You will need to create the records through other means
